### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Azorefr** [Stef-aap/RFLink-ESP#7]
Hi tank you for the job.
When i start compilation i have this issue.
In file included from sketch\Sensor_RFLink.h:22:0,

                 from sketch\Sensor_Receiver_2.h:692,

                 from D:\ESP_RFlink\RFLink_ESP_02\RFLink_ESP_02.ino:68:

sketch\RFLink\RFLink_File.h:8:24: fatal error: FS_support.h: No such file or directory
 #include "FS_support.h"
compilation terminated.
exit status 1
Erreur de compilation pour la carte NodeMCU 1.0 (ESP-12E Module)
I use Arduino IDE1.8.12 on Windows 10 and D:\ESP_RFlink\RFLink_ESP_02\RFLink.h exist well 

Best regards.

**Comment by Stef-aap** [comment]
hello,

ok this problem is caused by a different directory structure I'm using
.
The solution is simple, (because FS_Support.h is already included) you 
can skip (comment) line 8 in RF_Link_File.h

I'll upload this correction in a few minutes.

cheers, Stef

**Comment by Maikel-K** [comment]
Hi Stef,

I just downloaded the file and im trying to compile.
I selected RFLink_ESP_02.ino in Arduino IDE and the first error it gave me it was that the sketch needed to be in folder: RFLink_ESP_02, so i changed the name of the folder to contain _02. This fixed that. Then i compiled and it gave the following error:

In file included from sketch\Receiver_Telnet.h:6:0,

                 from sketch\Sensor_Receiver_2.h:201,

                 from C:\Users\xxxxx\Downloads\RFLink-ESP-master\RFLink-ESP-master\RFLink_ESP_02\RFLink_ESP_02.ino:68:

Receiver_Base.h:10:25: fatal error: ArduinoJson.h: No such file or directory

 #include <ArduinoJson.h>

                         ^

compilation terminated.

exit status 1
ArduinoJson.h: No such file or directory

**Comment by Maikel-K** [comment]
Nevermind, had to add the ArduinoJson library to Arduino IDE and i had to update the ESP8266 board manager. Upload succeeded.

I found RFLink_ESP hotspot. I connected. I recieved IP 192.168.6.85 and connected to http://192.168.6.84/

I got a MiRa sensor page. But no ESPeasy style webpage. Is that correct?

**Comment by Azorefr** [comment]
now the compilation is done well. Thank you.
There remains only to test!

**Comment by Stef-aap** [comment]
yes that's on the ToDo list: include a list of libraries used (and their 
version number), but unfortunatly this is not easy in Arduino)
