### ISSUE TITLE
MQTT with username and password

### ISSUE THREAD

**Issue by HomeBro** [Stef-aap/RFLink-ESP#8]
Hi Stef,

Thank you for keeping the idea of RFLink alive.

I've been using the Mega2560 version but it was so big a board and I missed the wifi option.

I've uploaded your code to a NodeMCu and a Wemos D1 and got it running, but my MQTT server requires an username and a password for connect to it. Where do I put that in your code?

What is the SSD1306 display code used for?

Regards,
Kim

**Comment by Stef-aap** [comment]
Username + Password forthe MQTT connection is now possible.

The SSD1306 is used to display information, example for the loop in the main program (so in that case you can not use the websettings for the moment)

// ****************************************************************************
// ****************************************************************************
unsigned long Send_Time_Last = -Send_Time_ms ;
void loop() {

  // ***********************************************************
  // call all loop methods
  // ***********************************************************
  Sensors  .loop () ;
  Receivers.loop () ;

  // ***********************************************************
  // for all sensors, get JSON-data and send to all active receivers
  // ***********************************************************
  if ( millis() - Send_Time_Last >= Send_Time_ms ) {
    Send_Time_Last = millis() ;   // geen noodzaak om in te halen !!
    Sensors.Get_JSON_Data () ;
    Receivers.Send_Data ( JSON_Data ) ;

    int    Value_Int   ;
    float  Value_Float ;
    String Value_String ;
    const int x2 = 6 ;
    DynamicJsonDocument jsonBuffer ( 600 ) ;   // PAS OP ALS TE KLEIN werkt het niet
    deserializeJson ( jsonBuffer, JSON_Data ) ;
 
   
    ( (_Receiver_SSD1306*)OLED )->Show ( Extra_Info                  , 0, 1, 2, 1 ) ;
    ( (_Receiver_SSD1306*)OLED )->Show ( String ( WiFi.localIP()[3] ), 3, 1, 3, 1 ) ;
   
    //  OLED_Display.setTextSize  ( 1 ) ;         
    Value_Int = jsonBuffer [ "MHZ14_CO2_ppm" ] ;
    ( (_Receiver_SSD1306*)OLED )->Show ( String ( Value_Int ), x2, 0, 4 ) ;
    //  OLED_Display.setTextSize  ( 2 ) ;         


    Value_Int   = jsonBuffer [ "ADC10" ] ;
    Value_Float = 1.2 * Value_Int / 1000 ;
    ( (_Receiver_SSD1306*)OLED )->Show ( String ( Value_Float, 1 ), x2, 2, 4 ) ;

    Value_Int   = jsonBuffer [ "ADC11" ] ;
    Value_Float = 1.2 * Value_Int / 1000 ;
    ( (_Receiver_SSD1306*)OLED )->Show ( String ( Value_Float, 1 ), x2, 3, 4 ) ;

    Value_Float = jsonBuffer [ "BME280_Temperature" ] ;
    ( (_Receiver_SSD1306*)OLED )->Show ( String ( Value_Float, 1 ),  0, 0, 4 ) ;


    String Extra = " %" ;
    if ( WiFi.localIP()[2] != 0 ) Extra = " %c" ;
    Value_Int = jsonBuffer [ "BME280_Humidity" ] ; //.as<int>() ;
    ( (_Receiver_SSD1306*)OLED )->Show ( String ( Value_Int ) + Extra,    0, 2, 5 ) ;

    Value_String = jsonBuffer [ "Time" ].as<String>() ;
    ( (_Receiver_SSD1306*)OLED )->Show ( Value_String.substring(0,5),    0, 3, 4 ) ;

  }
}
