### ISSUE TITLE
Code doesn't compile

### ISSUE THREAD

**Issue by plampix** [Stef-aap/RFLink-ESP#9]
Hi Stef,

When I try to compile the latest version, I get the following error message:

In file included from /tmp/arduino_build_668737/sketch/Sensor_Wifi.h:33:0,
                 from /tmp/arduino_build_668737/sketch/Sensor_Receiver_2.h:717,
                 from /home/peterp/src/Arduino/Stef-aap_RFLink-ESP/RFLink_ESP/RFLink_ESP.ino:74:
/tmp/arduino_build_668737/sketch/Wifi_Settings.h: In function 'void AddAccessPoints(ESP8266WiFiMulti*)':
Wifi_Settings.h:31:36: error: 'Local_Wifi_Name' was not declared in this scope
       _AddAccessPoint ( wifiMulti, Local_Wifi_Name  , Local_Wifi_PWD   );

I can't find any definition of Local_Wifi_Name in the source, shouldn't this be __SECRET_Wifi_Name instead?

**Comment by Stef-aap** [comment]
I think you're right (I renamed those constants.

At the moment I'm unable to double-check that.

**Comment by Stef-aap** [comment]
Thanks for finding this bug.

I handcrafted this file, because the original file contains all my 
Passowrds and other secrets

The file Wifi_Settings.h is corrected on Github.

**Comment by plampix** [comment]
Thanks!
